type: ChoiceQuestion
id: probid-qqid
value: 10
shuffle: true
prompt: |

        ### problem問題 No.qid

        作者 @
        現地点で未完成


choices:

  - ~CORRECT~ Answer-01
  - Answer-02
  - Answer-03
  - Answer-04

answer_explanation:
  Answer-01<br/>
